### ISSUE TITLE
Problems with results of image classification 

### ISSUE THREAD

**Issue by Keane-Mizzi** [jensleitloff/CNN-Sentinel#14]
I've been testing out the code and the training has been working as expected with both the pretrained and networks and custom on the eurostat dataset however, I've been having issues interpreting the results of the classifier. I also tried using the models that were provided on google drive as well as the image for prediction but I'm still facing the same issue. Any insight on this would be greatly appreciated.

The results I am getting are provided in the link below using the Models provided on google drive on other issues. 
(Results for my custom own training and prediction have been giving me very similar results)
https://drive.google.com/drive/folders/1UBRjIYioRjjB8kzHoNN0bt2M85jTifrE?usp=sharing

**Comment by felixriese** [comment]
Hi @Keane-Mizzi, 

What exactly is your question? How to open the output file? What output vectors are telling you? 

Please give us more input on how you are trying to interpret the data and what is irritating you.

Please also have a look at the already closed [issues](https://github.com/jensleitloff/CNN-Sentinel/issues?q=is%3Aissue+is%3Aclosed), since we have answered similar questions already and that might help you (e.g. #3, #4, #6).

Best,
Felix

**Comment by Keane-Mizzi** [comment]
Thanks for the reply, I'm not entirely sure what to do with the output files.

**Comment by felixriese** [comment]
Since you are not asking a precise question, I am not able to help you.

Further reading on land use classification can be found, e.g., in https://www.mdpi.com/2072-4292/13/1/78.
